apps/about/urls.py
from django.urls import path
from .views import about_view

app_name = "about"

urlpatterns = [
    path('', about_view, name='about')
]

apps/articles/urls.py
from django.urls import path
from .views import index, single_article, article, views_up

app_name = "articles"

urlpatterns = [
    path('', index, name='index'),
    path('blogs/', article, name='article'),
    path('views_up/<int:pk>/', views_up, name='views_up'),
    path('article/<int:pk>/', single_article, name='single-article'),
]

apps/contact/urls.py
from django.urls import path
from .views import contat_view
app_name = "contacts"

urlpatterns = [
    path('', contat_view, name='contact')
]

readit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.articles.urls", namespace="articles")),
    path('about/', include("apps.about.urls", namespace="about")),
    path('comment/', include("apps.comments.urls", namespace="comments")),
    path('contact/', include("apps.contact.urls", namespace="contacts")),

    path('api/', include("apps.articles.api.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/about/models.py
from django.db import models

# Create your models here.


class FeedBack(models.Model):
    name = models.CharField(max_length=222)
    position = models.CharField(max_length=222)
    avatar = models.ImageField(upload_to='about/')
    context = models.TextField()

    def __str__(self):
        return self.name

apps/contact/models.py
from django.db import models


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=221)
    email = models.EmailField()
    subject = models.CharField(max_length=221)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

apps/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

apps/about/views.py
from django.shortcuts import render
from .models import FeedBack
# Create your views here.


def about_view(request):
    happy_clients = FeedBack.objects.all()
    context = {"happy_clients": happy_clients}
    return render(request, 'about.html', context)

apps/contact/views.py
from django.shortcuts import render, redirect
from .models import Contact
from .forms import ContactForm


# Create your views here.


def _contat_view(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        Contact.objects.create(name=name, email=email, subject=subject, message=message)
        return redirect('contacts:contact')
    context = {}
    return render(request, 'contact.html', context)


def contat_view(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contacts:contact')
    context = {"form": form}
    return render(request, 'contact.html', context)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}

<section class="hero-wrap hero-wrap-2 js-fullheight"
         style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.7wX3e-PeJV.jpg' %})" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'articles:index' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end"
                     style="background-image:url({% static 'images/about.jpg' %});">
                    <a href="https://vimeo.com/45830194"
                       class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
                        <span class="icon-play"></span>
                    </a>
                </div>
            </div>
            <div class="col-md-6 pl-md-5 py-md-5">
                <div class="row justify-content-start pt-3 pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <span class="subheading">Welcome to Readit</span>
                        <h2 class="mb-4">We give you the best articles you want.</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <div class="tabulation-2 mt-4">
                            <ul class="nav nav-pills nav-fill d-md-flex d-block">
                                <li class="nav-item mb-md-0 mb-2">
                                    <a class="nav-link active py-2" data-toggle="tab" href="#home1">Our Mission</a>
                                </li>
                                <li class="nav-item px-lg-2 mb-md-0 mb-2">
                                    <a class="nav-link py-2" data-toggle="tab" href="#home2">Our Vision</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-2 mb-md-0 mb-2" data-toggle="tab" href="#home3">Our Value</a>
                                </li>
                            </ul>
                            <div class="tab-content bg-light rounded mt-2">
                                <div class="tab-pane container p-0 active" id="home1">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home2">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home3">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section testimony-section">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
                <span class="subheading">Testimonial</span>
                <h2 class="mb-4">Happy Clients</h2>
            </div>
        </div>
        <div class="row ftco-animate">
            <div class="col-md-12">
                <div class="carousel-testimony owl-carousel ftco-owl">
                    {% for item in happy_clients %}
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">{{ item.context|truncatewords_html:15 }}</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({{ item.avatar.url }})"></div>
                                    <div class="pl-3">
                                        <p class="name">{{ item.name }}</p>
                                        <span class="position">{{ item.position }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog single{% endblock %}

{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight"
         style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.7wX3e-PeJV.jpg' %})"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Blog Single</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                        href="{% url 'articles:article' %}">Blog <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p class="mb-5">
                    <img src="{{ article.image.url }}" alt="" class="img-fluid">
                </p>
                <h2 class="mb-3">{{ article.title }}</h2>
                <p>{{ article.context }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in article.tags.all %}
                        <a href="{% url 'articles:article' %}?tag={{ tag.title }}" class="tag-cloud-link">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="pt-5 mt-5">
                    {% if comments.count <= 1 %}
                    <h3 class="mb-5">{{ comments.count }} Comment</h3>
                    {% else %}
                    <h3 class="mb-5">{{ comments.count }} Comments</h3>
                    {% endif %}
                    <ul class="comment-list">
                        {% for item in comments %}
                        <li class="comment">
                            <div class="vcard bio">
                                {% if item.avatar %}
                                <img src="{{ item.avatar.url }}" alt="Image placeholder">
                                {% else %}
                                <img src="{% static 'images/xperson_1.jpg.pagespeed.ic.8e2vi2ER3S.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="comment-body">
                                <h3>{{ item.name }}</h3>
                                <div class="meta mb-3">{{ item.created_at }}</div>
                                <p>{{ item.message }}</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" class="p-5 bg-light" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <!--                            <div class="form-group">-->
                            <!--                                <label for="name">Name *</label>-->
                            <!--                                <input type="text" name="name" class="form-control" id="name">-->
                            <!--                            </div>-->
                            <!--                            <div class="form-group">-->
                            <!--                                <label for="email">Email *</label>-->
                            <!--                                <input type="email" name="email" class="form-control" id="email">-->
                            <!--                            </div>-->
                            <!--                            <div class="form-group">-->
                            <!--                                <label for="website">Website</label>-->
                            <!--                                <input type="image" name="avatar" class="form-control" id="website">-->
                            <!--                            </div>-->
                            <!--                            <div class="form-group">-->
                            <!--                                <label for="message">Message</label>-->
                            <!--                                <textarea name="message" id="message" cols="30" rows="10" class="form-control"></textarea>-->
                            <!--                            </div>-->
                            <div class="form-group">
                                <button type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">Send
                                    Comment
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form method="get" action="{% url 'articles:article' %}" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        {% for item in categories %}
                        <li><a href="{% url 'articles:article' %}?category={{ item.title }}">{{ item.title }}<span
                                class="ion-ios-arrow-forward"></span>
                            <div style="text-align:right">{{ item.n }}</div>
                        </a></li>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>
                    {% for item in recent_articles %}
                    <div class="block-21 mb-4 d-flex">
                        <a href="{% url 'articles:views_up' item.id %}" class="blog-img mr-4"
                           style="background-image:url({{ item.image.url }})"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{% url 'articles:views_up' item.id %}">{{ item.title }}</a></h3>
                            <div class="meta">
                                <div><a><span class="icon-calendar"></span>{{ item.created_at }}</a></div>
                                <div><a><span class="icon-person"></span> Admin</a></div>
                                <div><a><span class="icon-chat"></span>{{ item.views }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for item in tags %}
                        <a href="{% url 'articles:article' %}?tag={{ item.title }}" class="tag-cloud-link">{{ item.title }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% load params_tags %}

{% block content %}
<div class="hero-wrap js-fullheight"
     style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.7wX3e-PeJV.jpg' %})"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
             data-scrollax-parent="true">
            <div class="col-md-12 ftco-animate">
                <h2 class="subheading">Hello! Welcome to</h2>
                <h1 class="mb-4 mb-md-0">Readit blog</h1>
                <div class="row">
                    <div class="col-md-7">
                        <div class="text">
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                                there live the blind texts. Separated they live in Bookmarksgrove right at the coast of
                                the Semantics, a large language ocean.</p>
                            <div class="mouse">
                                <a href="#" class="mouse-icon">
                                    <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            {% for item in page_obj %}
            <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
                    <a href="{% url 'articles:views_up' item.id %}" class="block-20"
                       style="background-image:url({{ item.image.url }})">
                    </a>
                    <div class="text p-4 float-right d-block">
                        <div class="topper d-flex align-items-center">
                            <div class="one py-2 pl-3 pr-1 align-self-stretch">
                                <span class="day">{{ item.created_at|date:'d' }}</span>
                            </div>
                            <div class="two pl-0 pr-3 py-2 align-self-stretch">
                                <span class="yr">{{ item.created_at|date:"M" }}</span>
                                <span class="mos">{{ item.created_at|date:"Y" }}</span>
                            </div>
                        </div>
                        <h3 class="heading mb-3"><a href="{% url 'articles:views_up' item.id %}">{{ item.title }}</a></h3>
                        <p>{{ item.context|truncatewords_html:"15" }}</p>
                        <p><a href="{% url 'articles:views_up' item.id %}" class="btn-custom"><span
                                class="ion-ios-arrow-round-forward mr-3"></span>Read
                            more</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        {% if page_obj.has_other_pages %}

                        {% if page_obj.has_previous %}
<!--                        <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>-->
                        <li><a href="?{% url_encode page=page_obj.previous_page_number %}"><</a></li>
                        {% endif %}

                        {% for i in page_obj.paginator.page_range %}

                        {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }}</span></li>
                        {% elif i > page_obj.number|add:-2 and i < page_obj.number|add:2 %}
<!--                        <li><span><a href="?page={{ i }}">{{ i }}</a></span></li>-->
                        <li><span><a href="?{% url_encode page=i %}">{{ i }}</a></span></li>
                        {% endif %}

                        {% endfor %}

                        {% if page_obj.has_next %}
<!--                        <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>-->
                        <li><a href="?{% url_encode page=page_obj.next_page_number %}">&gt;</a></li>
                        {% endif %}

                        {% endif %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact{% endblock %}

{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight"
         style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.7wX3e-PeJV.jpg' %})" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Contact us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'articles:index' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section contact-section">
    <div class="container">
        <div class="row d-flex mb-5 contact-info">
            <div class="col-md-12 mb-4">
                <h2 class="h3">Contact Information</h2>
            </div>
            <div class="w-100"></div>
            <div class="col-md-3">
                <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
            </div>
            <div class="col-md-3">
                <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
            </div>
            <div class="col-md-3">
                <p><span>Email:</span> <a
                        href="https://preview.colorlib.com/cdn-cgi/l/email-protection#d9b0b7bfb699a0b6acabaab0adbcf7bab6b4"><span
                        class="__cf_email__"
                        data-cfemail="a8c1c6cec7e8d1c7dddadbc1dccd86cbc7c5">[email&#160;protected]</span></a></p>
            </div>
            <div class="col-md-3">
                <p><span>Website</span> <a href="#">yoursite.com</a></p>
            </div>
        </div>
        <div class="row block-9 no-gutters">
            <div class="col-lg-6 order-md-last d-flex">
                <form method="post" class="bg-light p-4 p-md-5 contact-form">
                    {% csrf_token %}
                    {{ form.as_p }}
<!--                    <div class="form-group">-->
<!--                        <input type="text" name="name" class="form-control" placeholder="Your Name">-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                        <input type="text" name="email" class="form-control" placeholder="Your Email">-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                        <input type="text" name="subject" class="form-control" placeholder="Subject">-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                        <textarea name="message" id="" cols="30" rows="7" class="form-control"-->
<!--                                  placeholder="Message"></textarea>-->
<!--                    </div>-->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary py-3 px-5">Send Message</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 d-flex">
                <div id="map" class="bg-white"></div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/footer.html
{% load static %}
{% load menu_foot %}
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="logo"><a href="#">Read<span>it</span>.</a></h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">latest News</h2>
                    {% show_foot %}
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="/" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home</a>
                        </li>
                        <li><a href="{% url 'articles:article' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Articles</a>
                        </li>
                        <li><a href="{% url 'about:about' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>About</a>
                        </li>
                        <li><a href="{% url 'contacts:contact' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="20494e464f60594f5552444f4d41494e0e434f4d">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/menu_foot.html
{% for item in articles %}
<div class="block-21 mb-4 d-flex">
    <a href="{% url 'articles:views_up' item.id %}" class="img mr-4 rounded" style="background-image: url({{ item.image.url }});"></a>
    <div class="text">
        <h3 class="heading"><a href="{% url 'articles:views_up' item.id %}">{{ item.title }}</a></h3>
        <div class="meta">
            <div><a href="#"></span> {{ item.created_at }}</a></div>
            <div><a href="#"></span> Admin</a></div>
            <div><a href="#"></span> {{ item.views }}</a></div>
        </div>
    </div>
</div>
{% endfor %}

templates/navbar.html
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/">Read<i>it</i>.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'articles:article' %}" class="nav-link">Articles</a></li>
                <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{% url 'contacts:contact' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>